Upgrade deps and swithch from commonjs -> module
digicatapult/dscp-api pull request #59
Opened 2022-10-17 10:33 UTC by mattdean-digicatapult

Upgrades deps to latest. `node-fetch` no longer supports commonjs giving us some impetous to switch to module syntax. A few notes from the upgrade:

* to import the package version from `package.json` we have to use new `import assert` syntax. Whilst nodejs supports this eslint requires a babel parser. Hence the inclusion of `@babel/eslint-parser` and `@babel/plugin-syntax-import-assertions`
* `node-fetch` no longer supports `form-data`. Switched to `formdata-node`
* `base-x` now returns a `Uint8Array` so we need to do some additional wrapping in a `Buffer`
* `mocharc.js` moved to `mocharc.cjs` as `mocha` does not support `import` syntax for this

2022-10-17 13:26 UTC, dblane-digicatapult requested changes

2022-10-17 13:26 UTC, dblane-digicatapult commented on package.json
> +    "@digicatapult/dscp-node": "^4.3.0",
4.3.1

2022-10-17 14:34 UTC, jonmattgray commented
Just noticed this repo is missing `depcheck` in its workflows. MIght be one for another PR

2022-10-18 07:53 UTC, n3op2 approved these changes
Did eslint updated all?

2022-10-18 08:10 UTC, dblane-digicatapult approved these changes

2022-10-18 08:40 UTC, merged